cloud:
  aws:
    s3:
      bucket: escape-user-bucket
      url: https://escape-user-bucket.s3.ap-northeast-2.amazonaws.com

    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB