server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j6c203.p.ssafy.io:8761/eureka

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "https://j6c203.p.ssafy.io"
            allow-credentials: true   #추가
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
      routes:
        - id: auth-server
          uri: http://j6c203.p.ssafy.io:8081/
          predicates:
            - Path=/api/auth-server/**
          filters:
            - RewritePath=/api/auth-server/(?<path>.*),/$\{path}
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway Logging filter
                preLogger: true
                postLogger: true
        - id: escape-server
          uri: http://j6c203.p.ssafy.io:8082/
          predicates:
            - Path=/api/escape-server/**
          filters:
            - RewritePath=/api/escape-server/(?<path>.*),/$\{path}
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway Logging filter
                preLogger: true
                postLogger: true
        - id: analysis-server
          uri: http://j6c203.p.ssafy.io:8083/
          predicates:
            - Path=/api/analysis-server/**
          filters:
            - RewritePath=/api/analysis-server/(?<path>.*),/$\{path}
            - name: LoggingFilter
              args:
                baseMessage: Spring Cloud Gateway Logging filter
                preLogger: true
                postLogger: true