server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: j6c203.p.ssafy.io
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/